
export const lightTheme = {
  dark: false,
  colors: {
    primary: "#8FABB7",
    secondary: '#f1e8e3',
    tertriary: "#cccfff",
    quatriary: '#cadfcf',
    background: "#FBFBFB",
    card: "#f3f3ff",
    text: "#000000",
    button: '#806491',
    border: "#CCC",
    inputBackground: "#F5F5F5",
    placeholderText:'#666666',
    selectedDayBackgroundColor: "#00adf5",
    selectedDayTextColor: "#ffffff",
    todayTextColor: "#00adf5",
    agendaDayTextColor: "#2d4150",
    agendaDayNumColor: "#00adf5",
    agendaKnobColor: "#00adf5",
    taskSelector:"f7f7f7",
    taskLabel:"91c7cc",
    picker:"91c7cc",
    fire:'#FFFAA0',
    fireBackground:'#FF8D7B',
    badge:'#FF8D7B',
    badgeBackground:'#FFFAA0'
  },
};

export const darkTheme = {
  dark: true,
  colors: {
    primary: "#91c7cc",
    secondary: "#3a3a3a",
    tertriary: "#4b4b4b",
    quatriary: "#2f2f2f",
    background: "#121212",
    card: "#1c1c1c",
    text: "#ffffff",
    button: '#f3f6f4',
    border: "#272727",
    inputBackground: "#2f2f2f",
    placeholderText:'#b3b3b3',
    selectedDayBackgroundColor: "#00adf5",
    selectedDayTextColor: "#ffffff",
    todayTextColor: "#00adf5",
    agendaDayTextColor: "#2d4150",
    agendaDayNumColor: "#00adf5",
    agendaKnobColor: "#00adf5",
    fire:'#FAFAFA',
    fireBackground:'#9D9D9D',
    badge:'#FAFAFA',
    badgeBackground:'#9D9D9D'
  },
};